<?php 

return [
    [
        'name' => 'La Trattoria del Borgo Dio',
        'description' => 'Autentica cucina italiana con specialità regionali.',
        'address' => 'Corso Vittorio Emanuele, 5',
        'p_iva' => '01234567890',
        'phone' => '+39 0123 456789',
        'image_url' => 'uploads/trattoria.png',
        'user_id' => 8,
    ],
    [
        'name' => 'Le Bistro Farisien',
        'description' => 'Gustosi piatti francesi in un\'atmosfera accogliente.',
        'address' => 'Via Roma, 10',
        'p_iva' => '09876543210',
        'phone' => '+39 9876 543210',
        'image_url' => 'uploads/kebab.jpg',
        'user_id' => 2,
    ],
    [
        'name' => 'Mamma Mia Pizzeria',
        'description' => 'Le migliori pizze cotte nel forno a legna secondo la tradizione napoletana.',
        'address' => 'Via Garibaldi, 20',
        'p_iva' => '24681357902',
        'phone' => '+39 0246 813579',
        'image_url' => 'uploads/pizzeria.jpg',
        'user_id' => 3,
    ],
[
        'name' => 'Sushiya',
        'description' => 'Specialità giapponesi fresche e deliziose preparate al momento.',
        'address' => 'Via Torquato Tasso',
        'p_iva' => '75395124680',
        'phone' => '+81 3 1234 5678',
        'image_url' => 'uploads/sushi.jpg',
        'user_id' => 4,
    ],
    [
        'name' => 'El Rancho Steakhouse',
        'description' => 'Tagli di carne succulenti e gustosi in un ambiente rustico.',
        'address' => 'Via dei Mercanti, 15',
        'p_iva' => '57904681324',
        'phone' => '+34 912 345 678',
        'image_url' => 'uploads/vegetariano1.png',
        'user_id' => 5,
    ],
    [
        'name' => 'Cantina Mexicana',
        'description' => 'Piatti autentici messicani con una vasta selezione di tequila.',
        'address' => 'Via dei Principati, 8',
        'p_iva' => '96123456780',
        'phone' => '+52 55 6789 1234',
        'image_url' => 'uploads/fast_food.jpg',
        'user_id' => 6,
    ],
    [
        'name' => 'Thai Spice',
        'description' => 'Esperienza culinaria thailandese con sapori autentici.',
        'address' => 'Via dei Canali, 23',
        'p_iva' => '46801357924',
        'phone' => '+66 2 3456 7890',
        'image_url' => 'uploads/cinese.jpg',
        'user_id' => 7,
    ]
];